In [1]:
#ignore warnings
import warnings
warnings.filterwarnings("ignore")

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
df = pd.read_csv("task1_dataset.csv")
df.head()

,date,age,income,loan_amount,credit_score,num_transactions,annual_spend,city,employment_type,loan_type,target
0,2020-01-01,63,63013.191704,279389.811431,616.029633,31,6.904324e+05,Bangalore,Unemployed,Auto,294319.227774
1,2020-01-02,20,47161.859481,950897.454063,716.561294,33,5.951086e+05,Bangalore,Student,Home,154516.648673
2,2020-01-03,46,55234.345094,NaN,564.991196,28,9.989912e+05,Delhi,Student,Auto,252354.507062
3,2020-01-04,52,74712.765160,431159.014692,572.736033,25,7.007800e+05,Chennai,Unemployed,Home,226719.203929
4,2020-01-05,56,82830.588108,272730.054365,813.630055,34,1.105784e+06,Delhi,Unemployed,Home,225838.346929

In [3]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              2000 non-null   object
 1   age               2000 non-null   int64
 2   income            1920 non-null   float64
 3   loan_amount       1920 non-null   float64
 4   credit_score      1920 non-null   float64
 5   num_transactions  2000 non-null   int64
 6   annual_spend      1920 non-null   float64
 7   city              2000 non-null   object
 8   employment_type   2000 non-null   object
 9   loan_type         2000 non-null   object
 10  target            2000 non-null   float64
dtypes: float64(5), int64(2), object(4)
memory usage: 172.0+ KB

date                 0
age                  0
income              80
loan_amount         80
credit_score        80
num_transactions     0
annual_spend        80
city                 0
employment_type      0
loan_type            0
target               0
dtype: int64

In [4]:
df.fillna(df.mean(numeric_only=True), inplace=True)
df.isnull().sum()

date                0
age                 0
income              0
loan_amount         0
credit_score        0
num_transactions    0
annual_spend        0
city                0
employment_type     0
loan_type           0
target              0
dtype: int64

In [5]:
df = df.drop("date", axis=1)
df.head()

,age,income,loan_amount,credit_score,num_transactions,annual_spend,city,employment_type,loan_type,target
0,63,63013.191704,279389.811431,616.029633,31,6.904324e+05,Bangalore,Unemployed,Auto,294319.227774
1,20,47161.859481,950897.454063,716.561294,33,5.951086e+05,Bangalore,Student,Home,154516.648673
2,46,55234.345094,313579.376380,564.991196,28,9.989912e+05,Delhi,Student,Auto,252354.507062
3,52,74712.765160,431159.014692,572.736033,25,7.007800e+05,Chennai,Unemployed,Home,226719.203929
4,56,82830.588108,272730.054365,813.630055,34,1.105784e+06,Delhi,Unemployed,Home,225838.346929

In [6]:
df = pd.get_dummies(df, drop_first=True)
df.head()

,age,income,loan_amount,credit_score,num_transactions,annual_spend,target,city_Chennai,city_Delhi,city_Hyderabad,city_Mumbai,employment_type_Self-Employed,employment_type_Student,employment_type_Unemployed,loan_type_Education,loan_type_Home,loan_type_Personal
0,63,63013.191704,279389.811431,616.029633,31,6.904324e+05,294319.227774,False,False,False,False,False,False,True,False,False,False
1,20,47161.859481,950897.454063,716.561294,33,5.951086e+05,154516.648673,False,False,False,False,False,True,False,False,True,False
2,46,55234.345094,313579.376380,564.991196,28,9.989912e+05,252354.507062,False,True,False,False,False,True,False,False,False,False
3,52,74712.765160,431159.014692,572.736033,25,7.007800e+05,226719.203929,True,False,False,False,False,False,True,False,True,False
4,56,82830.588108,272730.054365,813.630055,34,1.105784e+06,225838.346929,False,True,False,False,False,False,True,False,True,False

In [7]:
X = df.drop("target", axis=1)
y = df["target"]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)
r2_score(y_test, y_pred)

0.4081828549110178

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

grid = GridSearchCV(RandomForestRegressor(random_state=42),
                    param_grid,
                    cv=3,
                    n_jobs=-1)

grid.fit(X_train, y_train)

best_model = grid.best_estimator_
y_pred = best_model.predict(X_test)

from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.4142623906448586

In [13]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import r2_score

gb = GradientBoostingRegressor()
gb.fit(X_train, y_train)

y_pred = gb.predict(X_test)
r2_score(y_test, y_pred)

0.41476753155293333

In [14]:
from xgboost import XGBRegressor
from sklearn.metrics import r2_score

xgb = XGBRegressor(n_estimators=200, learning_rate=0.05, max_depth=5)
xgb.fit(X_train, y_train)

y_pred = xgb.predict(X_test)
r2_score(y_test, y_pred)

0.361362688170922

In [15]:
# remove less useful features
df_new = df.drop(['loan_type_Personal'], axis=1, errors='ignore')

X = df_new.drop("target", axis=1)
y = df_new["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [16]:
rf = RandomForestRegressor(n_estimators=300, max_depth=20, random_state=42)
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.4081571227640648

In [17]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score

best_score = 0
best_k = 0

for k in range(1, 21):
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_train, y_train)
    pred = knn.predict(X_test)
    score = r2_score(y_test, pred)
    
    if score > best_score:
        best_score = score
        best_k = k

best_k, best_score

(19, 0.12889024256485393)

In [20]:
gb = GradientBoostingRegressor()
gb.fit(X_train, y_train)

GradientBoostingRegressor()

In [19]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import r2_score

gb = GradientBoostingRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=5,
    subsample=0.8,
    random_state=42
)

gb.fit(X_train, y_train)

y_pred = gb.predict(X_test)
r2_score(y_test, y_pred)

0.36450222872758453

In [21]:
gb = GradientBoostingRegressor()
gb.fit(X_train, y_train)

GradientBoostingRegressor()

In [22]:
import joblib

joblib.dump(gb, "model.pkl")
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']

In [23]:
import joblib
joblib.dump(X.columns, "model_columns.pkl")

['model_columns.pkl']